version: "3"

dotenv:
  - configs/dev/.env

vars:
  organization_name: tasklify
  container_name: tasklify
  container_tag: latest

tasks:
  ## Golang, HTMX, Templ, TailwindCSS, YARN

  dev:
    deps:
      - task: deps
    cmds:
      - npx tailwindcss -c configs/tailwind.config.js -i configs/input.css -o static/css/style.css --watch &
      - docker compose -f deployments/docker-compose.yml -p tasklify up &
      - air -c configs/dev/.air.toml

  build:
    deps:
      - task: deps
      - task: generate
    cmds:
      - docker buildx build -t {{.organization_name}}/{{.container_name}}:{{.container_tag}} -f build/server/Dockerfile .

  deps:
    internal: true
    cmds:
      - yarn
      - cmd: mkdir -p static/{css,script}
        platforms: [linux, darwin]
      - cmd: cp node_modules/htmx.org/dist/htmx.min.js static/script/.
        platforms: [linux, darwin]
      - cmd: cp node_modules/htmx.org/dist/ext/response-targets.js static/script/.
        platforms: [linux, darwin]

      - cmd: powershell -Command "New-Item -ItemType Directory -Force -Path 'static\css', 'static\script'"
        platforms: [windows]
      - cmd: powershell -Command "Copy-Item -Path 'node_modules\htmx.org\dist\htmx.min.js', 'node_modules\htmx.org\dist\ext\response-targets.js' -Destination 'static\script\'"
        platforms: [windows]

  generate:
    internal: true
    cmds:
      - npx tailwindcss -c configs/tailwind.config.js -i configs/input.css -o static/css/style.css --minify
      - templ generate -include-version=false
      - go generate ./...

  ## Docker compose

  up:
    cmds:
      - docker compose -f deployments/docker-compose.yml -p tasklify --profile prod up -d {{.CLI_ARGS}}

  down:
    cmds:
      - docker compose -f deployments/docker-compose.yml -p tasklify down

  purge:
    cmds:
      - docker compose -f deployments/docker-compose.yml -p tasklify down --volumes
