// Code generated by templ - DO NOT EDIT.

package userstory

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "tasklify/internal/web/components/common"
import "fmt"
import "net/http"

func CreateUserStoryDialog(projectID uint) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\ndocument.getElementById('addAcceptanceTest').addEventListener('click', function() {\n    const container = document.getElementById('acceptanceTestsContainer');\n    const newFieldNumber = container.children.length;\n    const newField = document.createElement('input');\n    newField.setAttribute('type', 'text');\n    newField.setAttribute('name', 'acceptanceTests');\n    newField.setAttribute('class', 'input textarea textarea-bordered textarea-primary w-full max-w-s mt-1 mb-2');\n    container.appendChild(newField);\n});\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"https://github.com/tasklify/tasklify/tree/main?tab=readme-ov-file#creating-user-stories\" target=\"_blank\" class=\"help-button\" style=\"padding-right=10rem;\">?</a><!-- Title Field --> <div class=\"mb-4\"><label for=\"title\" class=\"block text-sm font-medium text-gray-700\">Title</label> <input type=\"text\" id=\"title\" name=\"title\" class=\"input input-bordered input-primary w-full max-w-s mt-1\" required></div><!-- Description Field --> <div class=\"mb-4\"><label for=\"description\" class=\"block text-sm font-medium text-gray-700\">Description</label> <textarea id=\"description\" name=\"description\" class=\"textarea textarea-bordered textarea-primary w-full max-w-s mt-1\" required></textarea></div><!-- Acceptance Tests Field --> <div id=\"acceptanceTestsContainer\"><label for=\"acceptanceTest0\" class=\"block text-sm font-medium text-gray-700\">Acceptance Tests:</label></div><button type=\"button\" id=\"addAcceptanceTest\" class=\"btn btn-primary btn-sm mb-2\">Add Acceptance Test</button><!-- Priority Field --> <div class=\"mb-4\"><label for=\"priority\" class=\"block text-sm font-medium text-gray-700\">Priority</label> <select id=\"priority\" name=\"priority\" class=\"select select-bordered select-primary w-full max-w-s mt-1\" required><option value=\"priority_must_have\">Must have</option> <option value=\"priority_should_have\">Should have</option> <option value=\"priority_could_have\">Could have</option> <option value=\"priority_wont_have_this_time\">Won't have this time</option></select></div><!-- Business Value Field --> <div class=\"mb-4\"><label for=\"business_value\" class=\"block text-sm font-medium text-gray-700\">Business Value:</label> <input type=\"number\" id=\"business_value\" name=\"business_value\" class=\"input input-bordered input-primary w-full max-w-s mt-1\" required></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = common.CreateDialog("Create user story", http.MethodPost, fmt.Sprintf("/%v/createuserstory", projectID), "Create").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
